### ISSUE TITLE
Plugin integration workflow

### ISSUE THREAD

**Issue by whyjay17** [rightpeter/CS565_Project#5]
@rightpeter 

The workflow of the plugin integration should be as follows:

1. If the user ignores the notification for the second time, it updates the ignore query in the DB.
-- the schema should be root - UID - ignore : { website: ... , endTime (?) ... } <-- forgot which time we were going to use, but I can manipulate it based on what you give me.

2. If the ignore query is updated on the DB, an event gets the trigger on the web app side and will update the calendar based on the ignore (add procrastination).

**Comment by rightpeter** [comment]
# Ignore message:
If the user doesn't respond to our notifications, after the second timeout, the plugin will update the ignore entry of that user on firebase.

        UIC.ignore:
        {
            website: youtube.com,
            endTime: 131423435234, (UTC timestamp)
        }

So the startTime for the procrastination will be `endTime - secondTimeOut`
